name: feedback

on: [fork, watch, issues]

jobs:
  feedback:

    runs-on: ubuntu-latest

    steps:
    - name: feedback
      id: feedback
      uses: d2-projects/repo-email-feedback@v1.0
      with:
        repo: ${{ github.repository }}
        actor: ${{ github.actor }}
        token: ${{ secrets.GITHUB_TOKEN }}